// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greetings.proto

package proto.greet;

public final class Greetings {
  private Greetings() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_greet_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_greet_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_greet_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_greet_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_greet_ResponseFromServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_greet_ResponseFromServer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017greetings.proto\022\013proto.greet\"1\n\007Messag" +
      "e\022\n\n\002to\030\001 \001(\t\022\014\n\004from\030\002 \001(\t\022\014\n\004text\030\003 \001(" +
      "\t\"\033\n\007Request\022\020\n\010username\030\001 \001(\t\"[\n\022Respon" +
      "seFromServer\022\017\n\007success\030\001 \001(\010\022\r\n\005error\030\002" +
      " \001(\t\022%\n\007message\030\003 \001(\0132\024.proto.greet.Mess" +
      "age2\224\001\n\013ChatService\022D\n\013SendMessage\022\024.pro" +
      "to.greet.Message\032\037.proto.greet.ResponseF" +
      "romServer\022?\n\017ReceiveMessages\022\024.proto.gre" +
      "et.Request\032\024.proto.greet.Message0\001B\002P\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_greet_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_greet_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_greet_Message_descriptor,
        new java.lang.String[] { "To", "From", "Text", });
    internal_static_proto_greet_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_greet_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_greet_Request_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_proto_greet_ResponseFromServer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_greet_ResponseFromServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_greet_ResponseFromServer_descriptor,
        new java.lang.String[] { "Success", "Error", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
