// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greetings.proto

package proto.greet;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.greet.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string to = 1;</code>
   * @return The to.
   */
  java.lang.String getTo();
  /**
   * <code>string to = 1;</code>
   * @return The bytes for to.
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>string from = 2;</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string text = 3;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 3;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
