// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greetings.proto

package proto.greet;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.greet.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
